!=======================================================================
!
!  Open and set up the log files used by UCL-PDR during its execution.
!
!-----------------------------------------------------------------------
SUBROUTINE OPEN_LOGFILES()

   USE HEALPIX_TYPES
   IMPLICIT NONE

   CHARACTER(LEN=256) :: FILENAME
   CHARACTER(LEN=8)   :: SUFFIX

   SUFFIX='.log'

   FILENAME=TRIM(ADJUSTL('main'))//TRIM(ADJUSTL(SUFFIX))
   OPEN(UNIT=10,FILE=FILENAME,STATUS='REPLACE')
   WRITE(10,"('Log of warning and error messages generated by UCL-PDR')")
   WRITE(10,*)

   FILENAME=TRIM(ADJUSTL('cvode'))//TRIM(ADJUSTL(SUFFIX))
   OPEN(UNIT=1,FILE=FILENAME,STATUS='REPLACE')
   WRITE(1,"('Log of warning and error messages generated by CVODE')")
   WRITE(1,*)
   CLOSE(1)

   RETURN
END SUBROUTINE OPEN_LOGFILES
!=======================================================================

!=======================================================================
!
!  Close the various log files used by UCL-PDR during its execution.
!
!-----------------------------------------------------------------------
SUBROUTINE CLOSE_LOGFILES()

   USE HEALPIX_TYPES
   IMPLICIT NONE

   CLOSE(10)

   RETURN
END SUBROUTINE CLOSE_LOGFILES
!=======================================================================
